name: kmp_petugas_app
description: Aplikasi KMP Petugas.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  another_flushbar: ^1.10.24
  cool_alert: ^1.1.0
  dartz: ^0.10.0
  device_info_plus: ^2.1.0
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  dots_indicator: ^2.0.0
  dotted_border: ^2.0.0+1
  dropdown_search: ^2.0.1
  equatable: ^2.0.3
  ext_storage:
    git:
      url: git://github.com/lavahasif/ext_storage_ups.git
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_dotenv: ^5.0.2
  flutter_form_bloc: ^0.20.6
  flutter_form_builder: ^6.1.0+1
  flutter_image_compress: ^1.1.0
  flutter_progress_hud: ^2.0.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  global_configuration: ^2.0.0-nullsafety.1
  grouped_list: ^4.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.3+1
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  percent_indicator: ^3.4.0
  permission_handler: 8.1.6
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.7
  super_easy_permissions: ^0.1.1
  syncfusion_flutter_charts: ^19.3.44+1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: 2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/cfg/
    - assets/icon/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
          weight: 400
        - asset: assets/font/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/font/Nunito-Bold.ttf
          weight: 700
        - asset: assets/font/Nunito-ExtraBold.ttf
          weight: 800
